import { Archive } from "@prisma/client";

export const mockArchiveData: Archive[] = [
  {
    id: "mock-1",
    title: "Summer Festival 2024",
    slug: "summer-festival-2024",
    description: "An unforgettable evening of music and dance at the annual summer festival",
    content: "The 2024 Summer Festival brought together over 500 community members for three days of live performances. Featured artists included local musicians, dancers, and emerging talent from the region.",
    URL: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2024-07-15"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "mock-2",
    title: "Community Garden Opening",
    slug: "community-garden-opening",
    description: "Local community comes together to launch new urban garden initiative",
    content: "Over 100 volunteers participated in planting day for the new downtown community garden. The space will feature seasonal vegetables, pollinator plants, and educational workshops.",
    URL: null,
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2024-05-20"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-10"),
  },
  {
    id: "mock-3",
    title: "Art Exhibition: Local Perspectives",
    slug: "art-exhibition-local-perspectives",
    description: "Showcasing works by 25 emerging artists from our community",
    content: "This month-long exhibition features paintings, sculptures, photography, and mixed media installations. All proceeds from art sales support local art education programs.",
    URL: null,
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2024-04-01"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "mock-4",
    title: "Winter Concert Series: Jazz Night",
    slug: "winter-concert-jazz-night",
    description: "Evening of smooth jazz and contemporary music from regional performers",
    content: "The Jazz Night featured three talented ensembles performing original compositions and classic standards. The intimate venue atmosphere created a perfect setting for an evening of musical excellence.",
    URL: "https://www.youtube.com/watch?v=example",
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2024-02-14"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "mock-5",
    title: "Documentary: Stories from Our Streets",
    slug: "documentary-stories-from-streets",
    description: "A 45-minute documentary featuring interviews with longtime community residents",
    content: "This documentary captures the history and spirit of our neighborhood through personal narratives. Viewers will discover hidden histories and inspiring stories of resilience and community.",
    URL: "https://www.youtube.com/watch?v=example2",
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2023-11-30"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-11-01"),
  },
  {
    id: "mock-6",
    title: "Annual Talent Show 2023",
    slug: "annual-talent-show-2023",
    description: "Community members showcase diverse talents and skills",
    content: "The 2023 Talent Show featured over 30 performances including music, dance, comedy, and spoken word. The event raised funds for the community youth center.",
    URL: null,
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2023-09-10"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2023-08-15"),
  },
  {
    id: "mock-7",
    title: "Historical Archives: Golden Age Photos",
    slug: "historical-archives-golden-age",
    description: "Restored photographs from the community's early years (1950s-1970s)",
    content: "A collection of beautifully restored historical photographs documenting the transformation of our neighborhood over five decades. Each image tells a story of change and continuity.",
    URL: null,
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2023-07-01"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2023-06-20"),
    updatedAt: new Date("2023-06-20"),
  },
  {
    id: "mock-8",
    title: "Spring Poetry Reading",
    slug: "spring-poetry-reading",
    description: "Emerging poets share original works in intimate cafes throughout town",
    content: "A multi-venue poetry series celebrating new voices in our community. Poets explored themes of renewal, identity, and social connection in this vibrant literary event.",
    URL: null,
    fileData: null,
    fileName: null,
    fileMimeType: null,
    fileSize: null,
    eventDate: new Date("2023-04-22"),
    isPublished: true,
    isApproved: true,
    createdAt: new Date("2023-04-01"),
    updatedAt: new Date("2023-04-01"),
  },
];

export function getMockArchives(): Archive[] {
  return mockArchiveData;
}

export function getMockArchiveById(id: string): Archive | undefined {
  return mockArchiveData.find((archive) => archive.id === id);
}
